services:
  reverse-proxy:
    container_name: traefik
    image: traefik:latest
    command:
      - --log.level=TRACE
      - --api.insecure=true
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entryPoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/custom.d/
      - --providers.file.watch=true
      - --certificatesresolvers.le.acme.tlschallenge=true
#      - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.le.acme.email=contact@ruinformatique.ch
      - --certificatesresolvers.le.acme.storage=/etc/traefik/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.ruinformatique.lan`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/ca/:/etc/ca/
      - ./conf/traefik/:/etc/traefik/
      - ./conf/traefik/resolv.conf:/etc/resolv.conf
    restart: "always"
