services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - "TZ= 'Europe/Zurich'"
      - "AUTO_UPDATE=false"
      - "PUID=1000"
      - "PGID=1001"
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.ruinformatique.lan`)"
      - "traefik.http.routers.radarr.tls=true"
    volumes:
      - "/data/radarr/config:/config"
      - "/mnt/plexus:/mnt/plexus"
      - "/mnt/plexus2:/mnt/plexus2"
    restart: always
  
  prowlarr:
    container_name: "prowlarr"
    image: "lscr.io/linuxserver/prowlarr:latest"
    environment:
      - "TZ= 'Europe/Zurich'"
      - "AUTO_UPDATE=false"
      - "PUID=1000"
      - "PGID=1001"
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.ruinformatique.lan`)"
      - "traefik.http.routers.prowlarr.tls=true"
    restart: "always"
    volumes:
      - "/data/prowlarr/config:/config"
  
  jackett:
    container_name: "jackett"
    image: "lscr.io/linuxserver/jackett:latest"
    environment:
      - "TZ= 'Europe/Zurich'"
      - "AUTO_UPDATE=false"
      - "PUID=1000"
      - "PGID=1000"
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.ruinformatique.lan`)"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.services.jackett.loadbalancer.server.port=80"
    restart: "always"
    volumes:
      - "/data/jackett/config:/config"
      - "/data/jackett/downloads:/downloads"

  plexus:
    container_name: "plexus"
    environment:
      - "PUID=1000"
      - "PGID=1001"
      - "TZ=Europe/Zurich"
    image: "jellyfin/jellyfin"
    group_add:
      - "989"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "8096:8096"
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - 'traefik.enable=true'
      - 'traefik.http.routers.plexus.entrypoints=websecure'
      - 'traefik.http.routers.plexus.rule=Host(`plexus.ruinformatique.ch`)'
      - 'traefik.http.routers.plexus.tls=true'
      - 'traefik.http.routers.plexus.tls.certresolver=le'
      - 'traefik.http.routers.plexus.tls.domains[0].main=ruinformatique.ch'
      - 'traefik.http.routers.plexus.middlewares=plexus-mw'
      - 'traefik.http.middlewares.plexus-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
      - 'traefik.http.middlewares.plexus-mw.headers.SSLRedirect=true'
      - 'traefik.http.middlewares.plexus-mw.headers.SSLHost=plexus.ruinformatique.ch'
      - 'traefik.http.middlewares.plexus-mw.headers.SSLForceHost=true'
      - 'traefik.http.middlewares.plexus-mw.headers.STSSeconds=315360000'
      - 'traefik.http.middlewares.plexus-mw.headers.STSIncludeSubdomains=true'
      - 'traefik.http.middlewares.plexus-mw.headers.STSPreload=true'
      - 'traefik.http.middlewares.plexus-mw.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.plexus-mw.headers.frameDeny=true'
      - 'traefik.http.middlewares.plexus-mw.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.plexus-mw.headers.customresponseheaders.X-XSS-PROTECTION=1'
      - "traefik.http.middlewares.plexus-mw.headers.customFrameOptionsValue='allow-from https://plexus.ruinformatique.ch'"
      - 'traefik.http.services.plexus-svc.loadBalancer.server.port=8096'
      - 'traefik.http.services.plexus-svc.loadBalancer.passHostHeader=true'
      - 'traefik.http.routers.plexus-insecure.entrypoints=websecure'
      - 'traefik.http.routers.plexus-insecure.rule=Host(`plexus.ruinformatique.ch`)'
      - 'traefik.http.routers.plexus-insecure.middlewares=plexus-insecure-mw'
      - 'traefik.http.middlewares.plexus-insecure-mw.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.plexus-insecure-mw.redirectscheme.permanent=false'
      - 'traefik.http.routers.plexus-insecure.service=noop@internal'
    restart: "always"
    volumes:
      - "/data/plexus/cache:/cache"
      - "/data/plexus/config:/config"
      - "/mnt/plexus:/mnt/plexus"
      - "/mnt/plexus2:/mnt/plexus2"

  sonarr:
    container_name: "sonarr"
    environment:
      - "TZ=Europe/Zurich"
      - "PUID=1000"
      - "PGID=1001"
    image: "lscr.io/linuxserver/sonarr:latest"
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.ruinformatique.lan`)"
      - "traefik.http.routers.sonarr.tls=true"
    restart: "always"
    volumes:
      - "/data/sonarr/config:/config"
      - "/mnt/plexus:/mnt/plexus"
      - "/mnt/plexus2:/mnt/plexus2"

        #  flaresolverr:
        #    container_name: "flaresolverr"
        #    image: "ghcr.io/flaresolverr/flaresolverr:latest"
        #    environment:
        #      - "TZ=Europe/Zurich"
        #      - LOG_LEVEL=${LOG_LEVEL:-info}
        #      - LOG_HTML=${LOG_HTML:-false}
        #      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
        #    labels:
        #      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
        #      - "traefik.enable=true"
        #      - "traefik.http.routers.solverr.rule=Host(`flaresolverr.ruinformatique.lan`)"
        #      - "traefik.http.routers.solverr.tls=true"
        #    restart: "always"

        #  qbittorrent:
        #    image: lscr.io/linuxserver/qbittorrent:latest
        #    container_name: qbittorrent
        #    environment:
        #      - PUID=1000
        #      - PGID=1000
        #      - TZ=Europe/Zurich
        #      - WEBUI_PORT=8080
        #      - TORRENTING_PORT=6881
        #    volumes:
        #      - "/mnt/downloads:/volume1/temp/downloadstation"
        #      - "/mnt/plexus:/mnt/plexus"
        #      - /data/qbittorrent/config:/config
        #      - /path/to/downloads:/downloads #optional
        #    ports:
        #      - 8080:8080
        #      - 6881:6881
        #      - 6881:6881/udp
        #    labels:
        #      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
        #      - "traefik.enable=true"
        #      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.ruinformatique.lan`)"
        #      - "traefik.http.routers.qbittorrent.tls=true"
        #      - 'traefik.http.services.qbittorrent.loadBalancer.server.port=8080'
        #    restart: unless-stopped
