version: "3"

# Phihole running in host mode ! may need to change interface

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "80:80/tcp"
      # - "443:443/tcp"
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
    environment:
      TZ: 'Europe/Zurich'
    volumes:
      - /data/pihole/etc-pihole/:/etc/pihole
      #- /data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    #cap_add:
    #  - NET_ADMIN
    restart: always


