services:
 kuma:
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`kuma.ruinformatique.lan`)"
      - "traefik.http.routers.kuma.tls=true"
    image: louislam/uptime-kuma:latest
    container_name: kuma
    restart: always
    volumes:
      - /data/kuma:/app/data

