tls:
  certificates:
    - certFile: /etc/ca/ruinformatique.lan/ruinformatique.lan.crt
      keyFile: /etc/ca/ruinformatique.lan/ruinformatique.lan.key
    - certFile: /etc/ca/ruinformatique.ch/ruinformatique.ch.pem
      keyFile: /etc/ca/ruinformatique.ch/ruinformatique.ch.key
